# Generated by Django 5.0.7 on 2024-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0002_guestorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='menus',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
