# Generated by Django 5.0.7 on 2024-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0005_remove_guestorder_created_at_remove_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='logoimage',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
