# Generated by Django 5.0.7 on 2024-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0008_remove_cafe_logoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
