# Generated by Django 5.0.7 on 2024-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0010_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
