# Generated by Django 5.0.7 on 2024-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0012_menuitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
