# Generated by Django 5.0.7 on 2024-08-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0014_guestorder_menu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestorder',
            old_name='menu_name',
            new_name='menu_item',
        ),
    ]
