# Generated by Django 5.0.7 on 2024-08-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0017_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestorder',
            name='menus',
        ),
    ]
